/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ComicSourceKeyIdRouteImport } from './routes/comic.$sourceKey.$id'
import { Route as ReadSourceKeyIdRouteImport } from './routes/read.$sourceKey.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ComicSourceKeyIdRoute = ComicSourceKeyIdRouteImport.update({
  id: '/comic/$sourceKey/$id',
  path: '/comic/$sourceKey/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadSourceKeyIdRoute = ReadSourceKeyIdRouteImport.update({
  id: '/read/$sourceKey/$id',
  path: '/read/$sourceKey/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/downloads': typeof DownloadsRoute
  '/library': typeof LibraryRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/comic/$sourceKey/$id': typeof ComicSourceKeyIdRoute
  '/read/$sourceKey/$id': typeof ReadSourceKeyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/downloads': typeof DownloadsRoute
  '/library': typeof LibraryRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/comic/$sourceKey/$id': typeof ComicSourceKeyIdRoute
  '/read/$sourceKey/$id': typeof ReadSourceKeyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/downloads': typeof DownloadsRoute
  '/library': typeof LibraryRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/comic/$sourceKey/$id': typeof ComicSourceKeyIdRoute
  '/read/$sourceKey/$id': typeof ReadSourceKeyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/downloads'
    | '/library'
    | '/search'
    | '/settings'
    | '/comic/$sourceKey/$id'
    | '/read/$sourceKey/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/downloads'
    | '/library'
    | '/search'
    | '/settings'
    | '/comic/$sourceKey/$id'
    | '/read/$sourceKey/$id'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/downloads'
    | '/library'
    | '/search'
    | '/settings'
    | '/comic/$sourceKey/$id'
    | '/read/$sourceKey/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  DownloadsRoute: typeof DownloadsRoute
  LibraryRoute: typeof LibraryRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  ComicSourceKeyIdRoute: typeof ComicSourceKeyIdRoute
  ReadSourceKeyIdRoute: typeof ReadSourceKeyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comic/$sourceKey/$id': {
      id: '/comic/$sourceKey/$id'
      path: '/comic/$sourceKey/$id'
      fullPath: '/comic/$sourceKey/$id'
      preLoaderRoute: typeof ComicSourceKeyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read/$sourceKey/$id': {
      id: '/read/$sourceKey/$id'
      path: '/read/$sourceKey/$id'
      fullPath: '/read/$sourceKey/$id'
      preLoaderRoute: typeof ReadSourceKeyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  DownloadsRoute: DownloadsRoute,
  LibraryRoute: LibraryRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  ComicSourceKeyIdRoute: ComicSourceKeyIdRoute,
  ReadSourceKeyIdRoute: ReadSourceKeyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
